{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId", "label": "traceId" }
  ]
 },
 "panels": [
  {
   "title": "Total Money",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "value_Total_money_made_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Purchased Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "items_purchased_Total_items_purchased_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Items Added to Cart",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "basket_add_to_cart_items_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Baskets To Placed Order",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(orders_Total_orders_number_total) * 100) / sum(baskets_created_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "order_processing_time_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}